## 10/13/22 Updated for Fedora 37
---

- name: Install software packages on Fedora 37
  hosts: all
  become: true
  tasks:
  - name: Install packages
    package:
      name:
        - gimp
        - neofetch
        - alligator
        - okular
        - neofetch
        - flameshot
        - wine
        - httpd
        - mariadb-server
        - git
      state: latest

  - name: Remove packages
    package:
      name:
        - rhythmbox
        - shotwell
      state: absent

  - name: Add a line to a file if the file does not exist, without passing regexp
    ansible.builtin.lineinfile:
      path: /tmp/testfile
      line: 192.168.1.99 foo.lab.net foo
      create: yes

  - name: Enable the Google Chrome repository
    dnf_repository:
      name: google-chrome
      state: present
      enabled: yes

  - name: Install Chrome
    package:
      name: google-chrome-stable
      state: latest

  - name: Install Steam on Fedora 37
    tasks:
  - name: Install dependencies
    package:
      name:
        - libtxc_dxtn
        - libglvnd-opengl
        - libglvnd-glx
        - libglvnd-egl
      state: latest

  - name: Download and install Steam
    get_url:
      url: https://steamcdn-a.akamaihd.net/client/installer/steam.sh
      dest: /tmp/steam.sh
      mode: 0755
    script: /tmp/steam.sh


  




