## updated 05/20/24 Updated for Fedora 40
---

 - name: Import vscode key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc  

 - name: create repo for vscode
    ansible.builtin.command: echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
  
  - name: Upgrade all packages
     ansible.builtin.dnf:
    name: "*"
    state: latest
 
  - name: install vscode
     ansible.builtin.dnf:
      name: code
      state: latest

- name: Install software packages on Fedora 40
  hosts: all
  become: yes
  tasks:
    - name: Install packages
      package:
        name:
          - gimp
          - neofetch
          - alligatorx
          - okular
          - flameshot
          - wine
          - httpd
          - mariadb-server
          - git
        state: latest

    - name: Remove packages
      package:
        name:

          - rhythmbox
          - shotwell
        state: absent

  
    - name: Install Steam on FC 40
      tasks:
        - name: Install dependencies
          package:
            name:
              - libtxc_dxtn
              - libglvnd-opengl
              - libglvnd-glx
              - libglvnd-egl
          state: latest

    - name: Download and install Steam
      get_url:
        url: https://steamcdn-a.akamaihd.net/client/installer/steam.sh
        dest: /tmp/steam.sh
        mode: 0755
      script: /tmp/steam.shell



  
