---
- hosts: localhost
  tasks:
    - name: install packages
      become: true
      become_user: root
      dnf:
        state: present
        name:
          - gimp
          - httpd
          - mariadb-server
          - flameshot
          - neofetch
          - okular
          - git
          - vlc

    - name: add fedora epel repo
      become: true
      become_user: root
      shell: dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
      ignore_errors: yes

    - name: get vscode key
      become: true
      become_user: root
      shell: rpm --import https://packages.microsoft.com/keys/microsoft.asc
      ignore_errors: yes

    - name: add vscode repo to dnf
      become: true
      become_user: root
      shell: dnf config-manager --add-repo https://packages.microsoft.com/yumrepos/vscode
      ignore_errors: yes

    - name: install vscode  
      become: true
      become_user: root
      dnf:
        state: present
        name: code 
        






      
   
